version: '3.8'

x-base: &base
  build:
    args:
      - USER_ID
      - GROUP_ID
    context: '.'
  volumes:
    - .:/usr/src/app

services:
  cargo:
    <<: *base
    entrypoint: cargo

  rustc:
    <<: *base
    entrypoint: rustc

  rustdoc:
    <<: *base
    entrypoint: rustdoc
